package futsal;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Orderan extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private ResultSet resultSet;
    private final String regex = "\\d+";

    private void viewData() {
        String cari = txtcari.getText();
        try {
            //koneksi ke database
            Connection con = Config.configDB();

            //Model tabel
            Object[] columnTitle = {"No", "Kode", "Nama Pemesan", "Nama Team", "No Telp", "Tanggal", "Jam", "Lama Bemain", "Harga"};
            tableModel = new DefaultTableModel(null, columnTitle);
            tbl_tabel.setModel(tableModel);
            tableModel.getDataVector().removeAllElements();

            //Buat statement
            Statement st = con.createStatement();
            int no = 1;
            resultSet = st.executeQuery("SELECT * FROM reservasi WHERE kode LIKE '%" + cari + "%'");
            while (resultSet.next()) {
                Object[] data = {
                    no++,
                    resultSet.getString("kode"),
                    resultSet.getString("namapemesan"),
                    resultSet.getString("namateam"),
                    resultSet.getString("notelp"),
                    resultSet.getString("tanggal"),
                    resultSet.getString("jam"),
                    resultSet.getInt("lamabermain"),
                    resultSet.getInt("harga")
                };
                tableModel.addRow(data);
            }
            con.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void kosong() { //untuk delete
        txtpemesan.setEditable(true);
        txtkode.setText(null);
        txtpemesan.setText(null);
        txtteam.setText(null);
        txtnotelp.setText(null);
        tanggal.setText(null);
        txtjam.setText(null);
        txtdurasi.setText(null);
        txtharga.setText(null);
        txtcari.setText(null);
    }

    public Orderan() {
        initComponents();
        viewData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabel = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtpemesan = new javax.swing.JTextField();
        txtteam = new javax.swing.JTextField();
        txtnotelp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdurasi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        txtjam = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 555));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        jLabel1.setText("Order Masuk");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 60));

        tbl_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Nama Pemesan", "Nama Team", "No Telp", "Tanggal", "Jam", "Lama Bermain", "Harga"
            }
        ));
        tbl_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 640, 150));

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 120, 35));

        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-google-web-search-30.png"))); // NOI18N
        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 35));

        btnubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-edit-30.png"))); // NOI18N
        btnubah.setText("Ubah Data");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 120, 35));

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-30.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, 35));

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, 35));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Reservasi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Pemesan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Tim");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No Telepon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, 20));
        getContentPane().add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 160, -1));
        getContentPane().add(txtpemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 160, -1));
        getContentPane().add(txtteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 160, -1));
        getContentPane().add(txtnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jam Mulai");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lama Bermain");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, 40));

        txtdurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdurasiActionPerformed(evt);
            }
        });
        getContentPane().add(txtdurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 160, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Harga");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 40, -1));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 160, -1));
        getContentPane().add(txtjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 160, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reservasigarisss (1).png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(750, 360));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtdurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdurasiActionPerformed

    private void tbl_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tabelMouseClicked
        // TODO add your handling code here:
        int baris = tbl_tabel.rowAtPoint(evt.getPoint());
        String kode = tbl_tabel.getValueAt(baris, 1).toString();
        txtkode.setText(kode);
        String namapemesan = tbl_tabel.getValueAt(baris, 2).toString();
        txtpemesan.setText(namapemesan);
        String namateam = tbl_tabel.getValueAt(baris, 3).toString();
        txtteam.setText(namateam);
        String notelp = tbl_tabel.getValueAt(baris, 4).toString();
        txtnotelp.setText(notelp);
        String Tanggal = tbl_tabel.getValueAt(baris, 5).toString();
        tanggal.setText(Tanggal);
        String jam = tbl_tabel.getValueAt(baris, 6).toString();
        txtjam.setText(jam);
        String lamabermain = tbl_tabel.getValueAt(baris, 7).toString();
        txtdurasi.setText(lamabermain);
        String harga = tbl_tabel.getValueAt(baris, 8).toString();
        txtharga.setText(harga);
    }//GEN-LAST:event_tbl_tabelMouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariKeyReleased

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE reservasi SET namapemesan='" + txtpemesan.getText() + "', "
                        + "namateam='" + txtteam.getText() + "', notelp='" + txtnotelp.getText() + "', "
                        + "Tanggal='" + tanggal.getText() + "', jam='" + txtjam.getText() + "', "
                        + "harga='" + txtharga.getText() + "'WHERE `kode`='" + txtkode.getText() + "'";

                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                viewData();
                JOptionPane.showMessageDialog(null, "berhasil mengubah data");
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        viewData();
    }//GEN-LAST:event_btncariActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try {
            String noHp = txtnotelp.getText();
            if (noHp.length() < 11 || noHp.length() > 13 || ((String.valueOf(noHp.charAt(0)).equals("0")) 
                    && String.valueOf(noHp.charAt(1)).equals("8")) != true) {
                txtnotelp.setText("");
                JOptionPane.showMessageDialog(null, "No Telepon Tidak Valid", "invalid", JOptionPane.ERROR_MESSAGE);
            } else if (noHp.matches(regex) != true) {
                txtnotelp.setText("");
                JOptionPane.showMessageDialog(null, "No Telepon Harus Angka", "invalid", JOptionPane.ERROR_MESSAGE);
            } else {
                String sql = "INSERT INTO `reservasi`(`kode`, `namapemesan`, `namateam`, `notelp`, `tanggal`, `jam`, "
                        + "`lamabermain`, `harga`) VALUES "
                        + "('" + txtkode.getText() + "','" + txtpemesan.getText() + "','" + txtteam.getText() + "',"
                        + "'" + txtnotelp.getText() + "','" + tanggal.getText() + "','" + txtjam.getText() + "',"
                        + "'" + txtdurasi.getText() + "','" + txtharga.getText() + "')";

                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                viewData();
                JOptionPane.showMessageDialog(null, "penyimpanan berhasil");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM reservasi where kode='" + txtkode.getText() + "'";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            viewData();
            JOptionPane.showConfirmDialog(null, "Apakah anda yakin menghapus data ini ?",
                    "Konfirmasi", JOptionPane.YES_NO_OPTION);
            JOptionPane.showMessageDialog(this, "berhasil di hapus");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());

            tbl_tabel();
            kosong();
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orderan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orderan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orderan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orderan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orderan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTable tbl_tabel;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtdurasi;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjam;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnotelp;
    private javax.swing.JTextField txtpemesan;
    private javax.swing.JTextField txtteam;
    // End of variables declaration//GEN-END:variables

    private void tbl_tabel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
